#服务端口
server:
  port: 8003
#服务名
spring:
  application:
    name: service-vod
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址
  #环境设置：dev、test、prod
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 1024MB #单个文件上传最大大小
      max-request-size: 1024MB #总上传文件大小
#阿里云 视频上传
#不同的服务器，地址不同
aliyun:
  vod:
    file:
      keyid: LTAI4GEYSSivCawpgPUeR3PG
      keysecret: iyENoW1eMXCZWUKgdMDT0GtLnrQH0n
