server:
  port: 8222
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启注册中心动态创建路由的功能，利用服务名路由
      routes:
        - id: service-edu     #路由id 建议配合服务名规则（不重复就可以）
          #uri: http://localhost:8001  # 匹配提供服务的路由地址
          uri: lb://service-edu  # 根据服务名路由
          predicates:
            - Path=/eduservice/**  #断言： 路由地址含该路径
        - id: service-acl
          uri: lb://service-acl
          predicates:
            - Path=/*/acl/**
#        - id: service-msm
#          uri: lb://service-msm  # 根据服务名路由
#          predicates:
#            - Path=/edu/msm/**
#        - id: service-order
#          uri: lb://service-order  # 根据服务名路由
#          predicates:
#            - Path=/orderservice
#        - id: service-ucenter
#          uri: lb://service-ucenter  # 根据服务名路由
#          predicates:
#            - Path=/educenter
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848