#服务端口
server:
  port: 8002
#服务名
spring:
  application:
    name: service-oss
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址
  #环境设置：dev、test、prod
  profiles:
    active: dev
#阿里云 OSS
#不同的服务器，地址不同
aliyun:
  oss:
    file:
      endpoint: oss-cn-shanghai.aliyuncs.com
      keyid: LTAI4GEYSSivCawpgPUeR3PG
      keysecret: iyENoW1eMXCZWUKgdMDT0GtLnrQH0n
      bucketname: myedu10
#bucket可以在控制台创建，也可以使用java代码创建
#aliyun.oss.file.bucketname=guli-file